"""
themes_en.py — English version: 72-theme translation map + stock name map
StockWaveJP English Edition
"""

# ── Theme name translation map (all 72 themes) ──
THEME_NAME_EN = {
    "半導体製造装置":         "Semiconductor Equipment",
    "半導体検査装置":         "Semiconductor Testing",
    "半導体材料":             "Semiconductor Materials",
    "メモリ":                 "Memory",
    "パワー半導体":           "Power Semiconductor",
    "次世代半導体":           "Next-Gen Semiconductor",
    "生成AI":                 "Generative AI",
    "AIデータセンター":       "AI Datacenter",
    "フィジカルAI":           "Physical AI",
    "AI半導体":               "AI Semiconductor",
    "AI人材":                 "AI Talent",
    "エッジAI":               "Edge AI",
    "EV・電気自動車":         "EV / Electric Vehicles",
    "全固体電池":             "All-Solid-State Battery",
    "自動運転":               "Autonomous Driving",
    "ドローン":               "Drones",
    "輸送・物流":             "Transport & Logistics",
    "造船":                   "Shipbuilding",
    "再生可能エネルギー":     "Renewable Energy",
    "太陽光発電":             "Solar Power",
    "核融合発電":             "Nuclear Fusion",
    "原子力発電":             "Nuclear Power",
    "電力会社":               "Electric Utilities",
    "LNG":                    "LNG",
    "石油":                   "Oil & Gas",
    "蓄電池":                 "Energy Storage",
    "資源（水素・ヘリウム・水）": "Resources (H2/He/H2O)",
    "IOWN":                   "IOWN",
    "光ファイバー・光部品":                 "Optical Fiber & Components",
    "通信":                   "Telecom",
    "量子コンピューター":     "Quantum Computing",
    "SaaS":                   "SaaS",
    "ウェアラブル端末":       "Wearables",
    "仮想通貨":               "Crypto",
    "ネット銀行":             "Digital Banking",
    "鉄鋼・素材":             "Steel & Materials",
    "化学":                   "Chemicals",
    "建築資材":               "Building Materials",
    "塗料":                   "Paints",
    "医薬品・バイオ":         "Pharma & Biotech",
    "ヘルスケア・介護":       "Healthcare & Nursing",
    "薬局・ドラッグストア":   "Pharmacy / Drug Store",
    "銀行・金融":             "Banking / Finance",
    "地方銀行":               "Regional Banks",
    "保険":                   "Insurance",
    "フィンテック":           "Fintech",
    "不動産":                 "Real Estate",
    "建設・インフラ":         "Construction & Infra",
    "国土強靭化計画":         "National Resilience",
    "下水道":                 "Water Infrastructure",
    "食品・飲料":             "Food & Beverage",
    "農業・フードテック":     "Agritech & Foodtech",
    "小売・EC":               "Retail & E-Commerce",
    "観光・ホテル・レジャー": "Tourism & Hotels",
    "インバウンド":           "Inbound Tourism",
    "リユース・中古品":       "Resale / Second-hand",
    "防衛・航空":             "Defense & Aerospace",
    "宇宙・衛星":             "Space & Satellite",
    "ロボット・自動化":       "Robotics & Automation",
    "レアアース・資源":       "Rare Earth & Resources",
    "バフェット銘柄":         "Buffett Picks",
    "サイバーセキュリティ":   "Cybersecurity",
    "警備":                   "Security Services",
    "脱炭素・ESG":            "Decarbonization / ESG",
    "教育・HR・人材":         "Education & HR",
    "人材派遣":               "Staffing / HR",
    "ゲーム・エンタメ":       "Gaming & Entertainment",
    "MLCC・電子部品":         "MLCC / Electronic Components",
    "電線・銅":               "Copper & Cable",
    "先端パッケージング・基板": "Advanced Packaging & PCB",
    "データセンター電力・冷却": "DC Power & Cooling",
    "M&A・事業承継":           "M&A & Succession",
}

# ── Stock name translation map ──
STOCK_NAME_EN = {
    "東京エレクトロン":     "Tokyo Electron",
    "アドバンテスト":       "Advantest",
    "ルネサス":             "Renesas Electronics",
    "ディスコ":             "Disco",
    "レーザーテック":       "Lasertec",
    "ソシオネクスト":       "Socionext",
    "マイクロニクス":       "Micronics Japan",
    "フェローテック":       "Ferrotec",
    "東京精密":             "Tokyo Seimitsu",
    "SCREEN HD":            "SCREEN HD",
    "芝浦メカトロニクス":   "Shibaura Mechatronics",
    "日立ハイテク":         "Hitachi High-Tech",
    "信越化学工業":         "Shin-Etsu Chemical",
    "SUMCO":                "SUMCO",
    "JSR":                  "JSR",
    "東京応化工業":         "Tokyo Ohka Kogyo",
    "住友化学":             "Sumitomo Chemical",
    "三菱ケミカルグループ": "Mitsubishi Chemical",
    "富士通":               "Fujitsu",
    "NEC":                  "NEC",
    "さくらインターネット": "Sakura Internet",
    "日立製作所":           "Hitachi",
    "オービック":           "Obic",
    "GMOインターネット":    "GMO Internet",
    "TIS":                  "TIS",
    "野村総合研究所":       "Nomura Research Institute",
    "SCSK":                 "SCSK",
    "ファナック":           "Fanuc",
    "安川電機":             "Yaskawa Electric",
    "キーエンス":           "Keyence",
    "デンソー":             "Denso",
    "ソニーグループ":       "Sony Group",
    "ルネサス":             "Renesas",
    "オムロン":             "Omron",
    "川崎重工業":           "Kawasaki Heavy",
    "THK":                  "THK",
    "トヨタ自動車":         "Toyota Motor",
    "パナソニックホールディングス": "Panasonic Holdings",
    "住友電気工業":         "Sumitomo Electric",
    "古河電気工業":         "Furukawa Electric",
    "村田製作所":           "Murata Manufacturing",
    "TDK":                  "TDK",
    "キオクシアHD":         "Kioxia HD",
    "三菱電機":             "Mitsubishi Electric",
    "ローム":               "Rohm",
    "富士電機":             "Fuji Electric",
    "東芝":                 "Toshiba",
    "サンケン電気":         "Sanken Electric",
    "三菱重工業":           "MHI",
    "IHI":                  "IHI",
    "川崎重工業":           "Kawasaki Heavy",
    "NTT":                  "NTT",
    "KDDI":                 "KDDI",
    "ソフトバンク":         "SoftBank Corp",
    "任天堂":               "Nintendo",
    "カプコン":             "Capcom",
    "バンダイナムコ":       "Bandai Namco",
    "スクウェア・エニックス": "Square Enix",
    "コナミ":               "Konami",
    "三菱UFJフィナンシャル・グループ": "MUFG",
    "三井住友フィナンシャルグループ": "SMFG",
    "みずほフィナンシャルグループ": "Mizuho FG",
    "東京海上ホールディングス": "Tokio Marine HD",
    "三菱地所":             "Mitsubishi Estate",
    "三井不動産":           "Mitsui Fudosan",
    "フジクラ":             "Fujikura",
    "INPEX":                "INPEX",
    "日本製鉄":             "Nippon Steel",
    "JFEホールディングス":  "JFE Holdings",
    "三井金属鉱業":         "Mitsui Mining & Smelting",
    "住友金属鉱山":         "Sumitomo Metal Mining",
    "第一三共":             "Daiichi Sankyo",
    "エーザイ":             "Eisai",
    "武田薬品工業":         "Takeda",
    "アステラス製薬":       "Astellas",
    "オリエンタルランド":   "Oriental Land",
    "モノタロウ":           "MonotaRO",
    "MoneyForward":         "MoneyForward",
    "Sansan":               "Sansan",
    "味の素":               "Ajinomoto",
    "日東紡績":             "Nittobo",
    "SKYパーフェクト・ジェイサット": "SKY Perfect JSAT",
}

# ── Extra themes (EN-only themes not in DEFAULT_THEMES) ──
EXTRA_THEMES_EN = {}

def translate_theme(name_ja: str) -> str:
    """テーマ名を英語に変換"""
    return THEME_NAME_EN.get(name_ja, name_ja)

def translate_stock(name_ja: str) -> str:
    """銘柄名を英語に変換"""
    return STOCK_NAME_EN.get(name_ja, name_ja)

def translate_themes_dict(themes: dict) -> dict:
    """DEFAULT_THEMESを英語キーに変換して返す"""
    result = {}
    for theme_ja, stocks in themes.items():
        theme_en = translate_theme(theme_ja)
        result[theme_en] = {
            translate_stock(k): v for k, v in stocks.items()
        }
    return result
