import { useEffect, useState } from 'react'
const KEY='swjp_en_onboarding_v1_shown', COOKIE='swjp_en_onboarding_v1_shown'
const STEPS=[
 {icon:'①',title:'Find strong themes',text:'Open Theme List, choose one week and rank by Market-Excess Return.'},
 {icon:'②',title:'Check breadth',text:'Use Theme Detail to compare volume, distribution and constituents.'},
 {icon:'③',title:'Compare stocks',text:'Use Stock Search and company disclosures to compare earnings, valuation and liquidity.'},
 {icon:'④',title:'Track continuation',text:'Use Reports to review whether prior leaders continued or reversed.'},
]
function seen(){try{if(localStorage.getItem(KEY)==='1')return true}catch{};try{return document.cookie.split(';').some(v=>v.trim()===`${COOKIE}=1`)}catch{return false}}
function remember(){try{localStorage.setItem(KEY,'1')}catch{};try{document.cookie=`${COOKIE}=1; Max-Age=31536000; Path=/; SameSite=Lax`}catch{}}
export default function FirstVisitTutorial({onNavigate}){const[open,setOpen]=useState(false),[step,setStep]=useState(0);useEffect(()=>{if(seen())return;remember();setOpen(true)},[]);if(!open)return null;const c=STEPS[step],btn=(background,color)=>({padding:'9px 14px',borderRadius:'7px',border:'1px solid var(--border)',background,color,cursor:'pointer',fontFamily:'var(--font)',fontWeight:700});return <div role="dialog" aria-modal="true" style={{position:'fixed',inset:0,zIndex:3000,background:'rgba(4,8,16,.78)',display:'grid',placeItems:'center',padding:'16px'}}><div style={{width:'min(560px,100%)',background:'var(--bg2)',border:'1px solid var(--border)',borderRadius:'14px',padding:'24px'}}><div style={{fontSize:'10px',color:'var(--accent)',fontWeight:800}}>FIRST-TIME GUIDE {step+1}/{STEPS.length}</div><div style={{fontSize:'36px',margin:'14px 0 8px'}}>{c.icon}</div><h2>{c.title}</h2><p style={{fontSize:'13px',color:'var(--text2)',lineHeight:1.9,minHeight:'74px'}}>{c.text}</p><div style={{display:'flex',justifyContent:'space-between',gap:'8px'}}><button onClick={()=>setOpen(false)} style={btn('transparent','var(--text3)')}>Close</button><div style={{display:'flex',gap:'8px'}}>{step>0&&<button onClick={()=>setStep(step-1)} style={btn('var(--bg3)','var(--text2)')}>Back</button>}{step<3?<button onClick={()=>setStep(step+1)} style={btn('var(--accent)','#fff')}>Next</button>:<button onClick={()=>{setOpen(false);onNavigate?.('Theme List')}} style={btn('var(--accent)','#fff')}>Open Theme List</button>}</div></div></div></div>}
