import React, { useState } from 'react'

const SECTIONS = [
  {
    icon:'📊', title:'Theme List',
    desc:'Compare price changes, volume and trading value across more than 72 Japanese equity themes.',
    items:[
      'Use the period selector at the top to change the analysis window. Available periods depend on your plan.',
      'The All-Theme Return Ranking shows the top four by default. Expand it to the top 10 or all themes.',
      'Monthly return, volume and trading-value charts can be enlarged on desktop. On mobile they remain optimized for the screen width.',
      'Select several themes to compare their monthly trends. Remove a theme by tapping its badge and add one with the Add Theme button.',
      'The heatmap summarizes return, volume acceleration and trading value. Hover on desktop or tap on mobile to inspect a bubble.',
    ],
  },
  {
    icon:'🔥', title:'Theme Heatmap',
    desc:'Visualize capital flow across 72 themes in a scatter-bubble chart.',
    items:[
      'The x-axis is return, the y-axis is volume acceleration, and bubble size represents trading value.',
      'The upper-right Hot Zone combines rising prices and accelerating volume. The upper-left is selling pressure, the lower-right is quiet appreciation and the lower-left is quiet weakness.',
      'Hover or tap a bubble to see the theme name, return, volume acceleration and trading value.',
      'The selected-theme panel below the chart shows return trend, volume trend, trading-value trend, median return, breadth, top three and worst three constituent stocks.',
      'Use the selector to switch between 1 day, 1 week, 1 month and 3 months.',
    ],
  },
  {
    icon:'🔍', title:'Theme Detail',
    desc:'Analyze the constituent stocks of an individual theme.',
    items:[
      'Choose a theme and period from the selectors at the top.',
      'Rising and falling top-five stocks and featured stocks are shown across the full width.',
      'On desktop, the lower section uses two columns: charts and navigation on the left, and the constituent table on the right.',
      'Sort the table by return, volume or trading value and switch ascending or descending order.',
      'The table supports horizontal scrolling and click-and-drag on desktop.',
      'Open charts in an enlarged view and add stocks to a custom theme with the plus button.',
    ],
  },
  {
    icon:'🎨', title:'Custom Themes',
    desc:'Build your own stock groups and track them as themes.',
    items:[
      'Free supports 1 theme with 10 stocks, Standard supports 5 themes with 20 stocks each, and Pro supports 10 themes with 50 stocks each.',
      'Search Japanese stocks by company name or four-digit ticker code.',
      'Google sign-in synchronizes themes across devices. Without sign-in, data is stored in browser LocalStorage.',
      'Custom-theme detail includes return and volume charts, a stock heatmap and a constituent table.',
      'Use Copy URL to share a custom theme.',
    ],
  },
  {
    icon:'📰', title:'Reports',
    desc:'Review theme rotation through weekly, monthly and quarterly reports.',
    items:[
      'Switch between weekly, monthly and quarterly reports from the tabs at the top.',
      'Weekly reports track subsequent performance of prior rankings and show excess performance versus the market proxy.',
      'Theme Detail and Read Column buttons appear near themes mentioned in the report.',
      'Tap a top-five or bottom-five theme badge to open that theme.',
      'Reports are manually prepared from market data rather than automatically generated by AI.',
    ],
  },
  {
    icon:'📝', title:'Columns & Analysis',
    desc:'Read detailed theme guides and related-company analysis.',
    items:[
      'All 72 themes have at least one explanatory article, with additional market and company analysis.',
      'Theme Detail pages link directly to relevant articles.',
      'The English edition also shows relevant overseas companies for supported themes.',
    ],
  },
  {
    icon:'⚙️', title:'Settings',
    desc:'Change appearance, layout and rising/falling color conventions.',
    items:[
      'Choose Dark or Light appearance.',
      'Choose automatic, mobile or desktop layout.',
      'Choose Japan colors (up red, down green) or US colors (up green, down red).',
      'Account deletion is placed at the bottom and requires two confirmation prompts.',
    ],
  },
]

const QA = [
  { q:'Is the market data real-time?', a:'No. Free uses the previous business day or the confirmed current-day close, Standard is scheduled at roughly 60-minute intervals, and Pro at roughly 15-minute intervals. Market holidays, the data provider and system processing can delay updates. Check Update Time, Data Time and Next Update at the top of the site.' },
  { q:'How are Featured Stocks selected?', a:'Stocks are scored mechanically using return, volume, price trend and trading value. The figures follow each plan’s update frequency and can differ from a brokerage trading screen.' },
  { q:'What units are used for trading value?', a:'Trading value is displayed in units such as ¥100 million or ¥1 trillion. Volume is the number of shares.' },
  { q:'How many Custom Themes can I create?', a:'Free: 1 theme and 10 stocks. Standard: 5 themes and 20 stocks per theme. Pro: 10 themes and 50 stocks per theme.' },
  { q:'What do the heatmap zones mean?', a:'Hot Zone: rising with accelerating volume. Sell Pressure: falling with accelerating volume. Quiet Rising: rising with limited volume. Quiet Falling: weak with limited activity.' },
  { q:'How is theme return calculated?', a:'Theme return is the simple average of constituent-stock returns. Individual stock returns are based on closing prices.' },
  { q:'How can I read wide tables on mobile?', a:'Swipe horizontally. Desktop also supports click-and-drag horizontal movement.' },
  { q:'What is the data source?', a:'After the commercial-data contract begins, price, volume and trading-value data are planned to come from Infoway’s Japan Stock Plan. Until then, some market data may be unavailable. Large-shareholding disclosures use public sources such as FSA EDINET.' },
]

function Chevron({open}) {
  return <svg width="16" height="16" viewBox="0 0 16 16" fill="none" style={{transition:'transform .2s',transform:open?'rotate(180deg)':'rotate(0deg)',flexShrink:0}}><path d="M4 6l4 4 4-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>
}

export default function HowTo() {
  const [openQ,setOpenQ]=useState(null)
  const [openS,setOpenS]=useState(null)
  return (
    <div style={{padding:'24px 28px 60px',maxWidth:'900px',margin:'0 auto'}}>
      <h1 style={{fontSize:'22px',fontWeight:700,color:'var(--text)',marginBottom:'6px'}}>📖 How to Use & FAQ</h1>
      <p style={{fontSize:'13px',color:'var(--text3)',marginBottom:'28px'}}>A practical guide to the current StockWaveJP workflow and features.</p>

      <div style={{marginBottom:'26px',padding:'16px 18px',background:'var(--bg2)',border:'1px solid var(--border)',borderRadius:'10px'}}>
        <div style={{fontSize:'14px',fontWeight:700,color:'var(--text)',marginBottom:'10px'}}>⏱️ Data Update Frequency by Plan</div>
        <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:'8px'}}>
          {[
            ['Free','Previous business day or confirmed close','#4a9eff'],
            ['Standard','About every 60 minutes','#ff8c42'],
            ['Pro','About every 15 minutes','#aa77ff'],
          ].map(([name,frequency,color])=><div key={name} style={{padding:'10px 12px',borderRadius:'8px',border:`1px solid ${color}35`,background:`${color}0d`}}><div style={{fontSize:'11px',fontWeight:800,color}}>{name}</div><div style={{fontSize:'12px',color:'var(--text2)',marginTop:'4px'}}>{frequency}</div></div>)}
        </div>
        <div style={{marginTop:'10px',fontSize:'10px',color:'var(--text3)',lineHeight:1.7}}>This is not second-by-second real-time data. Update times may vary on market holidays or when the provider is delayed.</div>
      </div>

      <div style={{marginBottom:'30px'}}>
        <h2 style={{fontSize:'16px',fontWeight:700,color:'var(--text)',marginBottom:'12px',borderBottom:'1px solid var(--border)',paddingBottom:'6px'}}>🧭 The Four-Step StockWaveJP Workflow</h2>
        <p style={{fontSize:'12px',color:'var(--text3)',lineHeight:1.8,marginBottom:'12px'}}>Use the four steps as one analysis cycle: discover a theme, test breadth, compare stocks and review the result.</p>
        <div className="howto-step-grid" style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:'10px'}}>
          {[
            ['1','Theme List','Set the period to one week and rank by market-excess return to find themes outperforming the broader market proxy.','Example: theme +3.2%, market proxy +1.0% = excess +2.2 points'],
            ['2','Theme Detail','Check volume, trading value, rising-stock ratio and the return distribution. Separate broad participation from a move driven by one company.','Example: a high average but low median can indicate concentration in a few winners'],
            ['3','Theme Detail & Stock Search','Narrow the constituents and verify earnings, orders, margins, valuation, liquidity and recent disclosures.','Example: equipment, materials and memory can sit in different semiconductor cycles'],
            ['4','Reports','Review subsequent performance of the prior ranking. Persistent excess performance supports continuation; a sharp reversal deserves reassessment.','Example: a prior No. 1 theme with -2.0 points of excess performance should not be chased blindly'],
          ].map(([n,page,body,example])=><div key={n} style={{padding:'16px',background:'var(--bg2)',border:'1px solid var(--border)',borderRadius:'10px',minHeight:'190px',display:'flex',flexDirection:'column'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:'8px'}}><span style={{fontSize:'10px',fontWeight:800,color:'var(--accent)'}}>STEP {n}</span><span style={{fontSize:'9px',fontWeight:700,color:'var(--accent)',padding:'2px 7px',borderRadius:'12px',background:'rgba(74,158,255,.08)',border:'1px solid rgba(74,158,255,.22)'}}>{page}</span></div><div style={{fontSize:'12px',fontWeight:700,color:'var(--text)',marginTop:'10px'}}>What to check</div><div style={{fontSize:'11px',color:'var(--text2)',lineHeight:1.8,marginTop:'6px',flex:1}}>{body}</div><div style={{fontSize:'10px',color:'var(--text3)',lineHeight:1.7,marginTop:'8px',paddingTop:'8px',borderTop:'1px dashed var(--border)'}}>{example}</div></div>)}
        </div>
      </div>

      <h2 style={{fontSize:'16px',fontWeight:700,color:'var(--text)',marginBottom:'14px',borderBottom:'1px solid var(--border)',paddingBottom:'6px'}}>🗺️ Feature Guide</h2>
      <div style={{display:'flex',flexDirection:'column',gap:'8px',marginBottom:'32px'}}>{SECTIONS.map((sec,si)=><div key={si} style={{background:'var(--bg2)',border:'1px solid var(--border)',borderRadius:'8px',overflow:'hidden'}}><button onClick={()=>setOpenS(openS===si?null:si)} style={{width:'100%',display:'flex',alignItems:'center',justifyContent:'space-between',gap:'12px',padding:'12px 16px',background:'transparent',border:'none',cursor:'pointer',textAlign:'left',fontFamily:'var(--font)',color:'var(--text)'}}><div style={{display:'flex',alignItems:'center',gap:'10px'}}><span style={{fontSize:'18px'}}>{sec.icon}</span><div><div style={{fontSize:'13px',fontWeight:700,color:'var(--text)'}}>{sec.title}</div><div style={{fontSize:'11px',color:'var(--text3)',marginTop:'2px'}}>{sec.desc}</div></div></div><Chevron open={openS===si}/></button>{openS===si&&<div style={{padding:'0 16px 14px',borderTop:'1px solid var(--border)'}}><ul style={{margin:'10px 0 0',paddingLeft:'20px',display:'flex',flexDirection:'column',gap:'5px'}}>{sec.items.map((item,ii)=><li key={ii} style={{fontSize:'12px',color:'var(--text2)',lineHeight:1.7}}>{item}</li>)}</ul></div>}</div>)}</div>

      <h2 style={{fontSize:'16px',fontWeight:700,color:'var(--text)',marginBottom:'14px',borderBottom:'1px solid var(--border)',paddingBottom:'6px'}}>❓ Frequently Asked Questions</h2>
      <div style={{display:'flex',flexDirection:'column',gap:'8px',marginBottom:'32px'}}>{QA.map((qa,i)=><div key={i} style={{background:'var(--bg2)',border:'1px solid var(--border)',borderRadius:'8px',overflow:'hidden'}}><button onClick={()=>setOpenQ(openQ===i?null:i)} style={{width:'100%',display:'flex',alignItems:'center',justifyContent:'space-between',gap:'12px',padding:'12px 16px',background:'transparent',border:'none',cursor:'pointer',textAlign:'left',fontFamily:'var(--font)',color:'var(--text)'}}><span style={{fontSize:'13px',fontWeight:600}}>Q. {qa.q}</span><Chevron open={openQ===i}/></button>{openQ===i&&<div style={{padding:'0 16px 14px',fontSize:'12px',color:'var(--text2)',lineHeight:1.8,borderTop:'1px solid var(--border)'}}><div style={{paddingTop:'10px'}}>A. {qa.a}</div></div>}</div>)}</div>
      <style>{`@media(max-width:640px){.howto-step-grid{grid-template-columns:1fr!important}}`}</style>
      <div style={{padding:'14px 18px',background:'rgba(255,193,7,.05)',border:'1px solid rgba(255,193,7,.2)',borderRadius:'8px',fontSize:'12px',color:'var(--text3)',lineHeight:1.8}}>⚠️ <strong style={{color:'var(--text2)'}}>Disclaimer: </strong>Information is provided for research purposes and is not a recommendation to buy or sell any security. Investment decisions remain the user’s responsibility.</div>
    </div>
  )
}
