// Shared theme name translation dictionary
export const THEME_NAME_EN = {
  '半導体製造装置': 'Semiconductor Equipment',
  '半導体検査装置': 'Semiconductor Testing',
  '半導体材料': 'Semiconductor Materials',
  'メモリ': 'Memory',
  'パワー半導体': 'Power Semiconductor',
  '次世代半導体': 'Next-Gen Semiconductor',
  '生成AI': 'Generative AI',
  'AIデータセンター': 'AI Datacenter',
  'フィジカルAI': 'Physical AI',
  'AI半導体': 'AI Semiconductor',
  'AI人材': 'AI Talent',
  'エッジAI': 'Edge AI',
  'EV・電気自動車': 'EV / Electric Vehicles',
  '全固体電池': 'All-Solid-State Battery',
  '自動運転': 'Autonomous Driving',
  'ドローン': 'Drones',
  '輸送・物流': 'Transport & Logistics',
  '造船': 'Shipbuilding',
  '再生可能エネルギー': 'Renewable Energy',
  '太陽光発電': 'Solar Power',
  '核融合発電': 'Nuclear Fusion',
  '原子力発電': 'Nuclear Power',
  '電力会社': 'Electric Utilities',
  'LNG': 'LNG',
  '石油': 'Oil & Gas',
  '蓄電池': 'Energy Storage',
  '資源（水素・ヘリウム・水）': 'Resources (H2/He/H2O)',
  'IOWN': 'IOWN',
  '光ファイバー・光部品': 'Optical Fiber & Components',
  '通信': 'Telecom',
  '量子コンピューター': 'Quantum Computing',
  'SaaS': 'SaaS',
  'ウェアラブル端末': 'Wearables',
  '仮想通貨': 'Crypto',
  'ネット銀行': 'Digital Banking',
  '鉄鋼・素材': 'Steel & Materials',
  '化学': 'Chemicals',
  '建築資材': 'Building Materials',
  '塗料': 'Paints',
  '医薬品・バイオ': 'Pharma & Biotech',
  'ヘルスケア・介護': 'Healthcare & Nursing',
  '薬局・ドラッグストア': 'Pharmacy / Drug Store',
  '銀行・金融': 'Banking / Finance',
  '地方銀行': 'Regional Banks',
  '保険': 'Insurance',
  'フィンテック': 'Fintech',
  '不動産': 'Real Estate',
  '建設・インフラ': 'Construction & Infra',
  '国土強靭化計画': 'National Resilience',
  '下水道': 'Water Infrastructure',
  '食品・飲料': 'Food & Beverage',
  '農業・フードテック': 'Agritech & Foodtech',
  '小売・EC': 'Retail & E-Commerce',
  '観光・ホテル・レジャー': 'Tourism & Hotels',
  'インバウンド': 'Inbound Tourism',
  'リユース・中古品': 'Resale / Second-hand',
  '防衛・航空': 'Defense & Aerospace',
  '宇宙・衛星': 'Space & Satellite',
  'ロボット・自動化': 'Robotics & Automation',
  'レアアース・資源': 'Rare Earth & Resources',
  'バフェット銘柄': 'Buffett Picks',
  'サイバーセキュリティ': 'Cybersecurity',
  '警備': 'Security Services',
  '脱炭素・ESG': 'Decarbonization / ESG',
  '教育・HR・人材': 'Education & HR',
  '人材派遣': 'Staffing / HR',
  'ゲーム・エンタメ': 'Gaming & Entertainment',
  '電線・銅': 'Copper & Cable',
  '先端パッケージング・基板': 'Advanced Packaging & PCB',
  'データセンター電力・冷却': 'DC Power & Cooling',
  'M&A・事業承継': 'M&A & Succession',
  'MLCC・電子部品': 'MLCC / Electronic Components',
}

export const tn = (name) => THEME_NAME_EN[name] || name
