create table if not exists public.legal_consents (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 terms_version text not null,
 privacy_version text not null,
 disclaimer_version text not null,
 locale text not null,
 source text not null,
 user_agent text,
 accepted_at timestamptz not null default now()
);
create index if not exists legal_consents_user_idx on public.legal_consents(user_id);
create unique index if not exists legal_consents_unique_acceptance
  on public.legal_consents(user_id,terms_version,privacy_version,disclaimer_version,source);
alter table public.legal_consents enable row level security;
grant select, insert, update on table public.legal_consents to authenticated;
grant usage, select on sequence public.legal_consents_id_seq to authenticated;
drop policy if exists "users read own legal consents" on public.legal_consents;
drop policy if exists "users insert own legal consents" on public.legal_consents;
drop policy if exists "users update own legal consents" on public.legal_consents;
create policy "users read own legal consents" on public.legal_consents for select to authenticated using (auth.uid()=user_id);
create policy "users insert own legal consents" on public.legal_consents for insert to authenticated with check (auth.uid()=user_id);
create policy "users update own legal consents" on public.legal_consents for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
